# Generated by Django 5.2.5 on 2025-08-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IRMImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('upload', models.FileField(upload_to='irm_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('png_preview', models.ImageField(blank=True, null=True, upload_to='irm_previews/')),
            ],
        ),
    ]
