# Generated by Django 5.2.5 on 2025-08-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_alter_irmimage_upload_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='irmimage',
            name='avc_type',
            field=models.CharField(blank=True, choices=[('ischémique', 'Ischémique'), ('hémorragique', 'Hémorragique')], max_length=20),
        ),
        migrations.AddField(
            model_name='irmimage',
            name='exam_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='irmimage',
            name='patient_name',
            field=models.CharField(default='2025-01-01', max_length=100),
            preserve_default=False,
        ),
    ]
