# Generated by Django 5.2.4 on 2025-08-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_irmimage_avc_type_irmimage_exam_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irmimage',
            old_name='upload',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='irmimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='irmimage',
            name='title',
        ),
        migrations.AlterField(
            model_name='irmimage',
            name='avc_type',
            field=models.CharField(blank=True, choices=[('ischémique', 'Ischémique'), ('hémorragique', 'Hémorragique'), ('inconnu', 'Inconnu')], max_length=20),
        ),
    ]
