# Generated by Django 5.2.5 on 2025-08-27 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_rapport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_scan', models.DateTimeField(auto_now_add=True)),
                ('nifti_file', models.FileField(upload_to='nifti_scans/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='viewer.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Coupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slices/')),
                ('numero_coupe', models.IntegerField()),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupes', to='viewer.scan')),
            ],
            options={
                'ordering': ['numero_coupe'],
            },
        ),
    ]
